# Generated by Django 6.1.1 on 2026-09-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seats',
            new_name='Seat',
        ),
        migrations.AddField(
            model_name='bus',
            name='no_of_seats',
            field=models.PositiveBigIntegerField(default=40),
            preserve_default=False,
        ),
    ]
